/**
 * Generated by Gfx v3.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (MyThing.as).
 */

package org.adarro.padx.client.javafx;

import java.io.Serializable;
import org.granite.messaging.annotations.Serialized;

@Serialized(propertiesOrder={  })
public class MyThingBase implements Serializable {

	private static final long serialVersionUID = 1L;
	

    
}