/**
 * Generated by Gfx v3.1.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package org.adarro.padx.client.javafx;

import org.granite.client.messaging.RemoteAlias;
import org.granite.messaging.annotations.Serialized;

@Serialized
@RemoteAlias("org.adarro.padx.client.javafx.MyThing")
public class MyThing extends MyThingBase {

    private static final long serialVersionUID = 1L;
}